## Time to play the puzzle

This week's puzzle: Take the last two letters of a state's capital city and the first two letters of the state. Rearrange them to name an activity that that state is associated with.

In [1]:
import pandas as pd
import csv
import itertools
from PyDictionary import PyDictionary

In [2]:
# Read in the data

df = pd.read_csv('capitals.csv', header=0, delimiter=';')
df.head()

,State,City,Capital,Since,Area (mi2),Proper,MSA/µSA,CSA,Rank in state
0,Alabama,Montgomery,1846,159.8,"199,000","386,047","476,207",3,NaN
1,Alaska,Juneau,1906,2716.7,"32,255","32,255",NaN,3,NaN
2,Arizona,Phoenix,1912,517.6,"1,597,000","4,845,832","4,899,104",1,NaN
3,Arkansas,Little Rock,1821,116.2,"206,000","748,031","912,604",1,NaN
4,California,Sacramento,1854,97.9,"516,000","2,397,382","2,680,831",6,NaN

In [3]:
states = df['State']
states.head()

0        Alabama
1         Alaska
2        Arizona
3       Arkansas
4     California
Name: State, dtype: object

In [4]:
cities = df['City']
cities.head()

0     Montgomery
1         Juneau
2        Phoenix
3    Little Rock
4     Sacramento
Name: City, dtype: object

In [5]:
#get the first two letters of state and last two letters of city. seem to have a leading space on states (whoops) hence the use of 1 & 2 rather than 0 & 1
letters = []
for i in range(len(states)):
    letter1 = states[i][1]
    letter2 = states[i][2]
    letter3 = cities[i][-1]
    letter4 = cities[i][-2]
    let = letter1.lower() + letter2 + letter3 + letter4
    letters.append(let)
letters

['alyr',
 'alua',
 'arxi',
 'arkc',
 'caot',
 'core',
 'codr',
 'dere',
 'flee',
 'geat',
 'haul',
 'ides',
 'ildl',
 'insi',
 'iose',
 'kaak',
 'ketr',
 'loeg',
 'maat',
 'masi',
 'mano',
 'mign',
 'milu',
 'mino',
 'miyt',
 'moan',
 'nenl',
 'neyt',
 'nedr',
 'neno',
 'neeF',
 'neyn',
 'nohg',
 'nokc',
 'ohsu',
 'okyt',
 'orme',
 'pegr',
 'rhec',
 'soai',
 'soer',
 'teel',
 'teni',
 'utyt',
 'vere',
 'vidn',
 'waai',
 'weno',
 'wino',
 'wyen']

In [6]:
#Get the different combinations of the letters

df_combos = pd.DataFrame()
for i in range(len(letters)):
    combos = []
    st = letters[i]
    per = itertools.permutations(st)
    for val in per:
        word = (val[0]+val[1]+val[2]+val[3])
        # print(*val)
        combos.append(word)
    # print(combos)
    ser = pd.Series(data=combos, name=states[i])
    df_combos[states[i]] = ser
df_combos

,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,Florida,Georgia,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
0,alyr,alua,arxi,arkc,caot,core,codr,dere,flee,geat,...,soer,teel,teni,utyt,vere,vidn,waai,weno,wino,wyen
1,alry,alau,arix,arck,cato,coer,cord,deer,flee,geta,...,sore,tele,tein,utty,veer,vind,waia,weon,wion,wyne
2,aylr,aula,axri,akrc,coat,croe,cdor,dree,fele,gaet,...,seor,teel,tnei,uytt,vree,vdin,waai,wneo,wnio,weyn
3,ayrl,aual,axir,akcr,cota,creo,cdro,dree,feel,gate,...,sero,tele,tnie,uytt,vree,vdni,waia,wnoe,wnoi,weny
4,arly,aalu,airx,acrk,ctao,ceor,crod,deer,fele,gtea,...,sroe,tlee,tien,utty,veer,vnid,wiaa,woen,woin,wnye
5,aryl,aaul,aixr,ackr,ctoa,cero,crdo,dere,feel,gtae,...,sreo,tlee,tine,utyt,vere,vndi,wiaa,wone,woni,wney
6,layr,laua,raxi,rakc,acot,ocre,ocdr,edre,lfee,egat,...,oser,etel,etni,tuyt,evre,ivdn,awai,ewno,iwno,ywen
7,lary,laau,raix,rack,acto,ocer,ocrd,eder,lfee,egta,...,osre,etle,etin,tuty,ever,ivnd,awia,ewon,iwon,ywne
8,lyar,luaa,rxai,rkac,aoct,orce,odcr,erde,lefe,eagt,...,oesr,eetl,enti,tyut,erve,idvn,aawi,enwo,inwo,yewn
9,lyra,luaa,rxia,rkca,aotc,orec,odrc,ered,leef,eatg,...,oers,eelt,enit,tytu,erev,idnv,aaiw,enow,inow,yenw
10,lray,laau,riax,rcak,atco,oecr,orcd,eedr,lefe,etga,...,orse,elte,eitn,ttuy,eevr,invd,aiwa,eown,iown,ynwe
11,lrya,laua,rixa,rcka,atoc,oerc,ordc,eerd,leef,etag,...,ores,elet,eint,ttyu,eerv,indv,aiaw,eonw,ionw,ynew
12,yalr,uala,xari,karc,ocat,rcoe,dcor,rdee,efle,aget,...,esor,etel,ntei,yutt,rvee,dvin,awai,nweo,nwio,ewyn
13,yarl,uaal,xair,kacr,octa,rceo,dcro,rdee,efel,agte,...,esro,etle,ntie,yutt,rvee,dvni,awia,nwoe,nwoi,ewny
14,ylar,ulaa,xrai,krac,oact,roce,docr,rede,elfe,aegt,...,eosr,eetl,neti,ytut,reve,divn,aawi,newo,niwo,eywn
15,ylra,ulaa,xria,krca,oatc,roec,dorc,reed,elef,aetg,...,eors,eelt,neit,yttu,reev,dinv,aaiw,neow,niow,eynw
16,yral,uaal,xiar,kcar,otca,reco,drco,rede,eefl,atge,...,erso,elte,nite,ytut,reve,dnvi,aiwa,nowe,nowi,enwy
17,yrla,uala,xira,kcra,otac,reoc,droc,reed,eelf,ateg,...,eros,elet,niet,yttu,reev,dniv,aiaw,noew,noiw,enyw
18,raly,aalu,iarx,cark,tcao,ecor,rcod,eder,efle,tgea,...,rsoe,ltee,iten,tuty,ever,nvid,iwaa,owen,owin,nwye
19,rayl,aaul,iaxr,cakr,tcoa,ecro,rcdo,edre,efel,tgae,...,rseo,ltee,itne,tuyt,evre,nvdi,iwaa,owne,owni,nwey
20,rlay,alau,irax,crak,taco,eocr,rocd,eedr,elfe,tega,...,rose,lete,ietn,ttuy,eevr,nivd,iawa,oewn,oiwn,nywe
21,rlya,alua,irxa,crka,taoc,eorc,rodc,eerd,elef,teag,...,roes,leet,ient,ttyu,eerv,nidv,iaaw,oenw,oinw,nyew
22,ryal,aual,ixar,ckar,toca,erco,rdco,erde,eefl,tage,...,reso,lete,inte,tyut,erve,ndvi,iawa,onwe,onwi,newy
23,ryla,aula,ixra,ckra,toac,eroc,rdoc,ered,eelf,taeg,...,reos,leet,inet,tytu,erev,ndiv,iaaw,onew,oniw,neyw

In [7]:
#export to csv
df_combos.to_csv('answers.csv')

In [8]:
dictionary = PyDictionary()

In [ ]:
# function to test if a string is in PyDictionary

# def test(str):
#     wordcheck = True
#     try:
#         if dictionary.meaning(str) == None:
#             wordcheck = False
#         # dictionary.meaning(str)
#     except:
#         wordcheck = False
#     return wordcheck


# test('helo')

# def test(str):
#     wordcheck = True
#     if dictionary.meaning(str) == None:
#         wordcheck = False
#     return wordcheck


# test('hello')

In [9]:
# NLTK dictionary

import nltk
from nltk.corpus import words

In [14]:
# Convert words from corpus to a set to make it faster (according to stackoverflow?)
wordset = set(words.words())

In [15]:
def test(str):
    wordcheck = False
    if str in wordset:
        wordcheck = True
    return wordcheck

test('hello')
# test('helo')

True

In [36]:
# Loop through df_combos
# Check if each item is a word
# If it's not a word, set it to "NAW" (or new txt file w/ State + Capital + word?)

for label, content in df_combos.items():
    # print(content)
    for index, value in content.items():
        # print(value)
        if test(value):
            print(label + ': ' + value)

 Alabama: aryl
 Alabama: lyra
 Alabama: yarl
 Alabama: ryal
 Alaska: aula
 Alaska: aula
 Arkansas: rack
 Arkansas: cark
 California: coat
 Colorado: core
 Colorado: cero
 Connecticut: cord
 Delaware: dere
 Delaware: deer
 Delaware: dree
 Delaware: dree
 Delaware: deer
 Delaware: dere
 Delaware: rede
 Delaware: reed
 Delaware: rede
 Delaware: reed
 Florida: flee
 Florida: flee
 Florida: feel
 Florida: feel
 Georgia: geat
 Georgia: geta
 Georgia: gaet
 Georgia: gate
 Hawaii: haul
 Hawaii: hula
 Idaho: ides
 Idaho: desi
 Idaho: side
 Illinois: dill
 Illinois: dill
 Kansas: kaka
 Kansas: kaka
 Kansas: kaka
 Kansas: kaka
 Kentucky: trek
 Louisiana: loge
 Louisiana: ogle
 Louisiana: egol
 Louisiana: goel
 Maine: atma
 Maine: atma
 Maryland: mias
 Maryland: saim
 Maryland: sima
 Massachusetts: mano
 Massachusetts: moan
 Massachusetts: mona
 Massachusetts: noma
 Michigan: ming
 Minnesota: limu
 Mississippi: mino
 Missouri: mity
 Montana: moan
 Montana: mona
 Montana: mano
 Montana: noma
 New Hampshire: dern
 New Hampshire: rend
 New Jersey: neon
 New Jersey: none
 New Jersey: neon
 New Jersey: none
 North Carolina: hong
 North Dakota: nock
 North Dakota: conk
 Ohio: huso
 Ohio: shou
 Oregon: omer
 Oregon: more
 Oregon: mero
 South Dakota: sore
 South Dakota: sero
 South Dakota: eros
 South Dakota: rose
 Tennessee: teel
 Tennessee: tele
 Tennessee: teel
 Tennessee: tele
 Tennessee: lete
 Tennessee: leet
 Tennessee: lete
 Tennessee: leet
 Texas: tien
 Texas: tine
 Texas: neti
 Vermont: veer
 Vermont: veer
 Vermont: ever
 Vermont: reve
 Vermont: reve
 Vermont: ever
 West Virginia: wone
 West Virginia: enow
 Wyoming: wyne